server:
  port: 8763

logging.level.root: TRACE

spring:
  application:
    name: auth

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

