server:
  port: 8081
  servlet.session.cookie.name : SPRINGJSESSIONID

spring:
  thymeleaf:
    cache: false
  application:
    name: edge

logging.level.root: TRACE

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/token
      userAuthorizationUri: http://localhost:8081/auth/authorize
      tokenName: oauth_token
      authenticationScheme: form
      clientAuthenticationScheme: form
      preEstablishedRedirectUri:
      useCurrentUri: true
    sso:
      loginPath: /login
    resource:
      token-info-uri: http://localhost:8081/auth/check_token

management:
  endpoints:
    web:
      exposure:
        include: routes,info